services:
  app:
    build:
      context: .
    container_name: face-widget
    ports:
      - ${PORT}:5000
    env_file: ".env"
    volumes:
      - ./images:/app/images
    deploy:
      restart_policy:
        condition: on-failure